<?php
require_once('../AWSSDKforPHP/rs-api-creds.php');
$ch = curl_init('https://my.rightscale.com/api/acct/51329/login?api_version=1.0');
curl_setopt($ch, CURLOPT_COOKIEJAR, '../tmp/rs_api_cookie.txt');
curl_setopt($ch, CURLOPT_USERPWD, 'darth.potater@gmail.com:Adm1nadm0n!');
curl_exec($ch);
curl_close($ch);
$url = 'https://my.rightscale.com/api/acct/51329/servers/292754001/stop_ebs';
$header = 'X-API-VERSION: 1.0';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_COOKIEFILE, '../tmp/rs_api_cookie.txt');
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,'api_version=1.0');
curl_exec($ch);
curl_close($ch);
$url = 'https://my.rightscale.com/api/acct/51329/servers/292885001/stop_ebs';
$header = 'X-API-VERSION: 1.0';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_COOKIEFILE, '../tmp/rs_api_cookie.txt');
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,'api_version=1.0');
curl_exec($ch);
curl_close($ch);
$url = 'https://my.rightscale.com/api/acct/51329/servers/292917001/stop_ebs';
$header = 'X-API-VERSION: 1.0';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_COOKIEFILE, '../tmp/rs_api_cookie.txt');
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,'api_version=1.0');
curl_exec($ch);
curl_close($ch);
$url = 'https://my.rightscale.com/api/acct/51329/servers/295067001/stop_ebs';
$header = 'X-API-VERSION: 1.0';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_COOKIEFILE, '../tmp/rs_api_cookie.txt');
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,'api_version=1.0');
curl_exec($ch);
curl_close($ch);
$url = 'https://my.rightscale.com/api/acct/51329/servers/297315001/stop_ebs';
$header = 'X-API-VERSION: 1.0';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_COOKIEFILE, '../tmp/rs_api_cookie.txt');
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,'api_version=1.0');
curl_exec($ch);
curl_close($ch);
