<?php
require_once('../AWSSDKforPHP/rs-api-creds.php');
$ch = curl_init('https://my.rightscale.com/api/acct/46971/login?api_version=1.0');
curl_setopt($ch, CURLOPT_COOKIEJAR, '../tmp/rs_api_cookie.txt');
curl_setopt($ch, CURLOPT_USERPWD, 'eric.adams@pearson.com:g0r3ds0x!');
curl_exec($ch);
curl_close($ch);
$url = 'https://my.rightscale.com/api/acct/46971/servers/420241001/_ebs';
$header = 'X-API-VERSION: 1.0';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_COOKIEFILE, '../tmp/rs_api_cookie.txt');
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,'api_version=1.0');
curl_exec($ch);
curl_close($ch);
$url = 'https://my.rightscale.com/api/acct/46971/servers/569036001/_ebs';
$header = 'X-API-VERSION: 1.0';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_COOKIEFILE, '../tmp/rs_api_cookie.txt');
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,'api_version=1.0');
curl_exec($ch);
curl_close($ch);
